test_logging_error: build a logger at the test level
test_logging_error calls getLogger at the module level and thus
a logger gets permanently inserted into the _loggers dict and is
visible in all other tests.
As tests shouldn't affect each other, a logger creation should be
moved to the TestLoggingFixture class setUp method.

Change-Id: I8e988c88cc1ffaf53bd3c97607f16fc2a8078d12