Convert unicode data to utf-8 before calling syslog.syslog()
Without this patch no conversion was taking place and message containing
special characters were raising TypeError exceptions. Just like the following
example:

>>> import syslog
>>> syslog.syslog(syslog.LOG_DEBUG, u"kaboom")
>>> syslog.syslog(syslog.LOG_DEBUG, u"François Deppierraz")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: [priority,] message string
>>>

Change-Id: I7557e016e8b9894033953bee689c79484c4a11f3
Closes-Bug: #1483842
(cherry picked from commit 93dd44f857b6b9546a8b52c9975a4ddb37bfc13c)