Fix mypy error
Fix the following error caused by recent typing support.

oslo_log/formatters.py:185:12: error: Redundant cast to "str"
[redundant-cast]

Change-Id: Iaf735ef4756d6180839756ef9958e6ab7b9b7774
Signed-off-by: Takashi Kajinami <kajinamit@oss.nttdata.com>