Fix new mypy errors
Fix the following error currently detected in master.

oslo_log/tests/unit/test_log.py:310:23: error: Argument 1 to
"skipUnless" has incompatible type Module; expected "bool"  [arg-type]

Change-Id: Ia15ef85e2987d2b8e1e3f3a16936b8200bf07cdc
Signed-off-by: Takashi Kajinami <kajinamit@oss.nttdata.com>
(cherry picked from commit d333016f740ec007c3502c17f6fc1599a54da1ae)