Fix the log test so it uses the available context fields.
logging_context_format_string in log.py references fields
that don't exist in the common/context.py so we get errors
like:

---
File "/usr/lib64/python2.7/logging/__init__.py", line 467, in format
    s = self._fmt % record.__dict__
KeyError: 'project_id'
Logged from file test_log.py, line 42
---

We could change the defaults in log.py but that might cause
too much disruption to other projects.

Change-Id: Ic3f6039baccb522b5eb2462a87b792c226ca13ef